categoria/urls.py
from django.urls import path
from .views import *

app_name = 'categoria'

urlpatterns = [
    path('', listar_categorias, name='listar_categorias'),
    path('cadastrar/', cadastrar_categorias, name='cadastrar_categorias'),
    path('categoria/<int:pk>/deletar', categoria_delete, name='categoria_delete'),
    path('categoria/<int:pk>/editar', categoria_edit, name='categoria_edit'),
]

moneyflow/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('categorias/', include('categoria.urls')),
    path('transacoes/', include('transacoes.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('usuarios/', include('usuarios.urls')),
]

usuarios/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('cadastro/', views.cadastro, name='cadastro'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

moneyflow/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Moneyflow</title>
    <link href="https://cdn.lineicons.com/4.0/lineicons.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="icon" type="image/png" sizes="40x40"
      href="{% static 'images/icone.png' %}">
    {% block extra_css %}{% endblock %}
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg py-4 py-lg-0 shadow">
            <div class="container px-4">
                <a href="{% url 'index' %}"><img src="{% static 'images/logo.svg' %}"></a>
                <button class="navbar-toggler border-0" type="button" data-bs-toggle="offcanvas" data-bs-target="#top-navbar" aria-controls="top-navbar">
                    <i class="lni lni-grid-alt"></i>
                </button>
                <div class="offcanvas offcanvas-end" tabindex="-1" id="top-navbar" aria-labelledby="top-navbarLabel">
                    <button class="navbar-toggler border-0" type="button" data-bs-toggle="offcanvas" data-bs-target="#top-navbar" aria-controls="top-navbar">
                        <div class="d-flex justify-content-between p-3">
                            <img src="{% static 'images/logo.svg' %}">
                            <i class="lni lni-cross-circle"></i>
                        </div>                    
                    </button>
                    <ul class="navbar-nav ms-lg-auto p-4 p-lg-0">
                        <li class="nav-item px-3 px-lg-0 py-1 py-lg-4">
                            <a class="nav-link" href="{% url 'index' %}">Home</a>
                        </li>
                        <li class="nav-item px-3 px-lg-0 py-1 py-lg-4">
                            <a class="nav-link" href="{% url 'categoria:listar_categorias' %}">Categorias</a>
                        </li>
                        <li class="nav-item px-3 px-lg-0 py-1 py-lg-4">
                            <a class="nav-link" href="{% url 'listar_transacoes' %}">Transações</a>
                        </li>
                        <li class="nav-item px-3 px-lg-0 py-1 py-lg-4">
                            <a class="nav-link" href="{% url 'dashboard' %}">Extrato</a>
                        </li>
                        <li class="nav-item px-3 px-lg-0 py-1 py-lg-4 dropdown">
                           <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Perfil</a>
                           <ul class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item">
                                        {% if user.is_authenticated %}
                                        {{ user.username }}
                                        {% else %}
                                        Perfil
                                        {% endif %}
                                    </a>
                                </li>
                                 {% if user.is_authenticated %}
                                <li>
                                    <a class="dropdown-item" href="{% url 'dashboard' %}">
                                    Meu painel
                                    </a>
                                </li>

                                <li>
                                    <a class="dropdown-item" href="{% url 'categoria:listar_categorias' %}">
                                    Minhas categorias
                                    </a>
                                </li>

                                <li><hr class="dropdown-divider"></li>

                                <li>
                                    <a class="dropdown-item text-danger" href="{% url 'logout' %}">
                                    Sair
                                    </a>
                                </li>

                                {% else %}
                                <li>
                                    <a class="dropdown-item" href="{% url 'login' %}">
                                    Entrar
                                    </a>
                                </li>

                                <li>
                                    <a class="dropdown-item" href="{% url 'cadastro' %}">
                                    Criar conta
                                    </a>
                                </li>
                                {% endif %}
                           </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer class="text-center py-4">
        <small>&copy; {% now "Y" %} MoneyFlow</small>
    </footer>
    {% block extra_js %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
</body>
</html>

moneyflow/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}
{% block content %}
  <section class="hero">
    <div class="hero-text">
      <h1>
        CONTROLE SEUS GASTOS <br>
        DE FORMA SIMPLES
      </h1>

      <p class="subtitle">
        Diga onde gastou, quanto gastou e <br>
        veja seu dinheiro fazer sentido.
      </p>

      <a href="{% url 'categoria:listar_categorias' %}" class="cta-btn">
        Classificar gastos
      </a>

      <p class="cta-description">
        Escolha uma categoria e registre seus gastos.
      </p>
    </div>
    <div class="hero-image">
      <!-- Troque o src pela sua imagem -->
      <img src="{% static 'images/grafico.png' %}" alt="Gráfico de crescimento financeiro">
    </div>

  </section>
  <section class="container my-5">

  <div class="row g-4">

    <div class="col-md-4">
      <div class="card h-100 shadow-sm">
        <div class="card-body">
          <h5 class="card-title">Planeje seus objetivos</h5>
          <h6 class="card-subtitle mb-2 text-body-secondary">
            Clareza financeira
          </h6>
          <p class="card-text">
            Ao organizar seus gastos por categoria, você entende
            para onde seu dinheiro vai e planeja objetivos com mais segurança.
          </p>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="card h-100 shadow-sm">
        <div class="card-body">
          <h5 class="card-title">Evite surpresas no fim do mês</h5>
          <h6 class="card-subtitle mb-2 text-body-secondary">
            Controle mensal
          </h6>
          <p class="card-text">
            Visualize seus gastos ao longo do mês e evite estourar
            o orçamento sem perceber.
          </p>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="card h-100 shadow-sm">
        <div class="card-body">
          <h5 class="card-title">Decida com base em dados</h5>
          <h6 class="card-subtitle mb-2 text-body-secondary">
            Consciência financeira
          </h6>
          <p class="card-text">
            Com tudo registrado, suas decisões deixam de ser no
            impulso e passam a ser mais conscientes.
          </p>
        </div>
      </div>
    </div>

  </div>

</section>
{% endblock %}