categoria/urls.py
from django.urls import path
from .views import *

app_name = 'categoria'

urlpatterns = [
    path('', listar_categorias, name='listar_categorias'),
    path('cadastrar/', cadastrar_categorias, name='cadastrar_categorias'),
    path('categoria/<int:pk>/deletar', categoria_delete, name='categoria_delete'),
    path('categoria/<int:pk>/editar', categoria_edit, name='categoria_edit'),
]

moneyflow/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('categorias/', include('categoria.urls')),
    path('transacoes/', include('transacoes.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('usuarios/', include('usuarios.urls')),
]

usuarios/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('cadastro/', views.cadastro, name='cadastro'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

categoria/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Categoria(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,related_name='categorias')
    nome = models.CharField(max_length=100)
    tipo = models.CharField(
        max_length=7,
        choices=[
            ('entrada', 'Entrada'),
            ('saida', 'Saída'),
        ]
    )
    descricao = models.TextField(blank=True)
   
    class Meta:
        unique_together = ('user', 'nome')
        

    def __str__(self):
        return f"{self.nome} ({self.tipo})"

categoria/forms.py
from django import forms
from .models import Categoria

class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['nome', 'tipo', 'descricao']
        widgets = {
            'descricao': forms.Textarea(attrs={
                'rows': 3,
                'placeholder': 'Ex: gastos com mercado, lanches e refeições'
            })
        }

categoria/views.py
from .models import Categoria
from .forms import CategoriaForm
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

@login_required
def listar_categorias(request):
    categorias = Categoria.objects.filter(user=request.user)
    return render(request, 'categoria/listar_categorias.html', {'categorias': categorias})

@login_required
def cadastrar_categorias(request):
    if request.method == 'POST':
        form = CategoriaForm(request.POST)
        if form.is_valid():
            categoria=form.save(commit=False)
            categoria.user = request.user
            categoria.save() 
            return redirect('categoria:listar_categorias')
    else:
        form = CategoriaForm()
    return render(request, 'categoria/cadastrar_categoria.html', {'form': form})

@login_required
def categoria_delete(request, pk):
    categoria = get_object_or_404(Categoria, pk=pk, user=request.user)

    if request.method == "POST":
        categoria.delete()

    return redirect('categoria:listar_categorias')

@login_required
def categoria_edit(request, pk):
    categoria = get_object_or_404(Categoria, pk=pk, user=request.user)
    
    if request.method == 'POST':
        form = CategoriaForm(request.POST, instance=categoria)
        if form.is_valid():
            form.save()
            return redirect('categoria:listar_categorias')
    else:
        form = CategoriaForm(instance=categoria)
        
    return render(request, 'categoria/editar_categoria.html', {'form': form, 'categoria': categoria})


# Create your views here.

categoria/templates/categoria/cadastrar_categoria.html
{% extends "base.html" %}
{% block content %}
<h1>Cadastrar nova Categoria</h1>

<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Enviar</button>

</form>
{% endblock %}

categoria/templates/categoria/editar_categoria.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/categoria.css' %}">
{% endblock %}

{% block content %}

<section class="categoria-container">
    <div class="categoria-card">
        <header class="categoria-header">
            <h1>Editar Categoria</h1>
            <p>Altere a descrição de sua categoria</p>
        </header>


        <form method="POST" class="categoria-form">
            {% csrf_token %}


            <div class="form-group">
                <label for="id_nome">Nome</label>
                {{ form.nome }}
            </div>


            <div class="form-group">
                <label for="id_tipo">Tipo</label>
                {{ form.tipo }}
            </div>


            <div class="form-group">
                <label for="id_descricao">Descrição</label>
                {{ form.descricao }}
            </div>


            <div class="form-actions">
                <button type="submit" class="btn-primary">Salvar edição</button>
                    <a href="{% url 'categoria:listar_categorias' %}" class="btn-secondary">Cancelar</a>
            </div>
        </form>
    </div>
</section>

{% endblock %}

categoria/templates/categoria/listar_categorias.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/categoria.css' %}">
{% endblock %}

{% block content %}

<section class="categories-hero">
  <div class="categories-text">
    <h1>
      SUAS <br>
      CATEGORIAS
    </h1>

    <p class="subtitle">
      Organize seus gastos criando categorias <br>
      que fazem sentido para sua realidade.
    </p>

    <a href="{% url 'categoria:cadastrar_categorias' %}" class="cta-btn">
      Criar nova categoria
    </a>
  </div>
</section>

<section class="categories-list container my-5">
  <div class="row g-4">

    {% for catego in categorias %}
      <div class="col-md-4">
        <div class="category-card">
          <h5>{{ catego.nome }}</h5>

          <p>
            {{ catego.descricao|default:"Use esta categoria para classificar seus gastos de forma organizada." }}
          </p>

          <div class="card-actions">
            <a href="{% url 'adicionar_transacao' %}?categoria={{catego.id}}" class="category-link">
              Nova transação
            </a>

            <a href="{% url 'categoria:categoria_edit' catego.id %}" class="category-edit-btn">
              Editar
            </a>

            <form method="post" action="{% url 'categoria:categoria_delete' catego.id %}">
              {% csrf_token %}
              <button type="submit" class="category-delete-btn" 
                      onclick="return confirm('Tem certeza que deseja excluir?');">
                Excluir
              </button>
            </form>
          </div>
        </div>     
      </div>
  {% endfor %}

  </div>
</section>

{% endblock %}